server:
  port: 80
  servlet:
    context-path: /
spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  mvc:
    view:
      suffix: .html
  resources:
    static-locations: file:./html/